index:
  path: /{_locale}
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

contact:
  path: /{_locale}/contact
  controller: App\Controller\DefaultController::contact
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

boutique:
  path: /{_locale}/boutique
  controller: App\Controller\BoutiqueController:index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr
rayon:
  path: /{_locale}/rayon/{idCategorie}
  controller: App\Controller\BoutiqueController:rayon
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr
    idCategorie: '1'

search:
  path: /{_locale}/search
  controller: App\Controller\BoutiqueController:search
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr
    search: 'oreo'

panier:
  path: /{_locale}/panier
  controller: App\Controller\PanierController:index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locate: fr

panier_ajouter:
  path: /{_locale}/panier/ajouter/{idProduit}/{quantite}
  controller: App\Controller\PanierController:ajouter
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr
    quantite: 1

panier_retirer:
  path: /{_locale}/panier/retirer/{idProduit}/{quantite}
  controller: App\Controller\PanierController:retirer
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr
    quantite: 1

panier_supprimer:
  path: /{_locale}/panier/supprimer/{idProduit}
  controller: App\Controller\PanierController:supprimer
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

panier_validation:
  path: /{_locale}/panier/valider
  controller: App\Controller\PanierController:validation
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

usager_index:
  path: /{_locale}/usager/accueil
  controller: App\Controller\UsagerController:index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

usager_inscription:
  path: /{_locale}/usager/inscription
  controller: App\Controller\UsagerController:new
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr